//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OA_ItemEntities : DbContext
    {
        public OA_ItemEntities()
            : base("name=OA_ItemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ApprovalDescibe> ApprovalDescibe { get; set; }
        public DbSet<ApprovalForm> ApprovalForm { get; set; }
        public DbSet<AttendanceRecordInfo> AttendanceRecordInfo { get; set; }
        public DbSet<AttendanceSheet> AttendanceSheet { get; set; }
        public DbSet<departmentInfo> departmentInfo { get; set; }
        public DbSet<MailboxTable> MailboxTable { get; set; }
        public DbSet<NoticeInfo> NoticeInfo { get; set; }
        public DbSet<PermissionsInfo> PermissionsInfo { get; set; }
        public DbSet<PositionInfo> PositionInfo { get; set; }
        public DbSet<PremissAsUser> PremissAsUser { get; set; }
        public DbSet<SalaryTable> SalaryTable { get; set; }
        public DbSet<UserInfo> UserInfo { get; set; }
    }
}
