//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string LoginName { get; set; }
        public string UserPwd { get; set; }
        public Nullable<int> UserAge { get; set; }
        public Nullable<int> UserSex { get; set; }
        public string UserTel { get; set; }
        public string UserEmail { get; set; }
        public string UserAddress { get; set; }
        public string BuMenId { get; set; }
        public Nullable<int> ZhiWeiId { get; set; }
        public string EntryTime { get; set; }
        public string QuitId { get; set; }
        public string XueLi { get; set; }
        public Nullable<int> OccupationalStatus { get; set; }
        public string UserNum { get; set; }
    }
}
